#!/bin/bash

NODE_COUNT=4
op=$1

if [ -z $op ]
then
    echo "usage: `basename $0` [start|stop]"
    exit 1
fi

i=0
while [ $i -lt $NODE_COUNT ]
do 
    if [ -f ./bin/atom$i ]
    then
        ./bin/atom$i $op
        if [ $? -eq 0 ]
        then
            sleep 1
        fi
    fi
    i=$(($i+1));
done

