#!/bin/bash
# Run this from the top level BOD project dir.

. env.sh
. build_args.sh

WORK_DIR=`pwd`

if [ -z $PLATFORM_DEPLOY_DIR ]
then
    echo -n "$0 error: "
    echo "Please set PLATFORM_DEPLOY_DIR in env.sh"
    exit 1
fi

if [ ! -f "${PLATFORM_DEPLOY_DIR}" ]
then
    sudo mkdir -p "${PLATFORM_DEPLOY_DIR}"
    sudo chmod 775 "${PLATFORM_DEPLOY_DIR}"
    sudo -E chown ${LOGNAME} "${PLATFORM_DEPLOY_DIR}"
    sudo chgrp adm "${PLATFORM_DEPLOY_DIR}"
fi

OLD_UI_DIR="${WORK_DIR}/"gwt/ui/war
UI_DIR="${WORK_DIR}/"`find gwt/ui/target -name platform-gwt-ui-* -type d`
ENG_DIR="${WORK_DIR}/"`find engine/target -name platform-engine-* -type d`

META_DIR="${ENG_DIR}/"META-INF
WEB_DIR="${ENG_DIR}/"WEB-INF

if [ 1 -eq ${DEV_BUILD} ]
then
    if [ 1 -eq ${DEPLOY_GWT_2_0} ]
    then
        RPC_DIR="${OLD_UI_DIR}/"AtomSphere
        RPCW_DIR="${OLD_UI_DIR}/"WidgetSphere
        MDM_DIR="${OLD_UI_DIR}/"MdmSphere
        RPCA_DIR="${OLD_UI_DIR}/"ApiSphere
    else
        RPC_DIR="${UI_DIR}/"AtomSphere
        RPCW_DIR="${UI_DIR}/"WidgetSphere
        MDM_DIR="${UI_DIR}/"MdmSphere
        RPCA_DIR="${UI_DIR}/"ApiSphere
    fi
else
    RPC_DIR="${ENG_DIR}/"AtomSphere
    RPCW_DIR="${ENG_DIR}/"WidgetSphere
    MDM_DIR="${ENG_DIR}/"MdmSphere
    RPCA_DIR="${ENG_DIR}/"ApiSphere
fi

DIRS=("${META_DIR}" "${WEB_DIR}" "${RPC_DIR}" "${RPCW_DIR}" "${RPCA_DIR}" "${MDM_DIR}")

echo
echo Deploying platform from "${WORK_DIR}"
echo
for DIR in ${DIRS[@]}
do
    echo $DIR
    rm -rf "${PLATFORM_DEPLOY_DIR}/""`basename ${DIR}`"
    ln -s -t "${PLATFORM_DEPLOY_DIR}" "${DIR}"
    echo
done

# create the jetty context, needed so that jetty will follow symlinks
temp_xml=/tmp/ROOT.xml
context_xml="${PLATFORM_DEPLOY_DIR}".xml

if [ ! -f "${context_xml}" ]; then
  cat > "${temp_xml}" <<'endmsg'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
  <Set name="contextPath">/</Set>
  <Set name="war"><Property name="jetty.webapps" default="."/>/ROOT</Set>

  <Call name="addAliasCheck">
    <Arg><New class="org.eclipse.jetty.server.handler.AllowSymLinkAliasChecker"/></Arg>
  </Call>

</Configure>
endmsg

sudo mv "${temp_xml}" "${context_xml}"

fi

