#!/bin/bash
# Run this from the top level BOD project dir.

. env.sh

WORK_DIR=`pwd`
echo Deploying platform from "${WORK_DIR}"

if [ -z $PLATFORM_DEPLOY_DIR ]
then
    echo -n "$0 error: "
    echo "Please set PLATFORM_DEPLOY_DIR in env.sh"
    exit 1
fi

APP_DIR=`find gwt/ui/target -name platform-gwt-ui-* -type d`
DEPLOY_BASE="${WORK_DIR}"/"${APP_DIR}"

META_DIR="${DEPLOY_BASE}"/META-INF
WEB_DIR="${DEPLOY_BASE}"/WEB-INF

if [ "$1" == "--gwt" ]
then
    RPC_DIR="${WORK_DIR}"/gwt/ui/war/AtomSphere
    RPCW_DIR="${WORK_DIR}"/gwt/ui/war/WidgetSphere
    MDM_DIR="${WORK_DIR}"/gwt/ui/war/MdmSphere
else
    RPC_DIR="${DEPLOY_BASE}/"AtomSphere
    RPCW_DIR="${DEPLOY_BASE}/"WidgetSphere
    MDM_DIR="${DEPLOY_BASE}/"MdmSphere
fi

DIRS=("${META_DIR}" "${WEB_DIR}" "${RPC_DIR}" "${RPCW_DIR}" "${MDM_DIR}")

for DIR in ${DIRS[@]}
do
    echo $DIR
    rm -rf "${PLATFORM_DEPLOY_DIR}"/"`basename ${DIR}`"
    ln -s -t "${PLATFORM_DEPLOY_DIR}" "${DIR}"
    echo
done

