echo "public class $1 extends $2"
echo "{"
echo ""
echo "    private static final long serialVersionUID = `date +%Y%m%d`;"
echo ""
echo "    public $1()"
echo "    {"
echo "        super();"
echo "    }"
echo ""
echo "    public $1(String message)"
echo "    {"
echo "        super(message);"
echo "    }"
echo ""
echo "    public $1(String message, Exception cause)"
echo "    {"
echo "        super(message, cause);"
echo "    }"
echo "}"
echo ""

