#!/bin/bash

defaultsession=default
session=${1:-$defaultsession}

function new-window
{
   tmux new-window
   tmux rename-window "${1}"
   tmux send-keys "cd ${2}" 'C-m'
}

sessions=`tmux list-sessions`
if [ 0 -eq $? ]
then
    grep -E "^${session}" <<< $sessions
    if [ $?  -eq 0 ]
    then
        tmux attach -t "${session}"
        exit 0
    fi
fi

echo "starting new session named ${session}"

cd ~/src/git.rs.ring.com/
tmux -2 new-session -d -s "${session}"

#customize first window
tmux rename-window 'hub-build'
tmux send-keys 'cd ../vagrant' 'C-m'
tmux send-keys 'vagrant up'
tmux send-keys 'vagrant ssh' 'C-m'

#create the rest
new-window 'hub remote' '.'
new-window 'hub remote' '.'
new-window 'hub-core' 'hub-core/hub-core'
new-window 'c++' 'hub-core/hub-core'
new-window 'redsky' 'hub-core/plugin-redsky'
new-window 'go' 'go'
new-window 'cell services' 'go/cell-services'
new-window 'java' 'java'
new-window 'asset services' 'java/asset-services'

tmux attach -t "${session}"

exit 0
