#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "Installs all the distribution files from a local container build to a local platform instance."
    echo 
    echo "Usage: $0 [-c <container_dir>] [-u <update_dir>] <build_number>"
    exit 0
fi

CONTAINER_DIR="/home/jason/Projects/atom"
UPDATE_DIR="/var/lib/tomcat6/updates"

while [ $# -gt 1 ] ; do

    CL_ARG=$1
    shift

    case ${CL_ARG} in

        -c)
            CONTAINER_DIR=$1
            shift
            ;;

        -u)
            UPDATE_DIR=$1
            shift
            ;;
        *)
            echo "Unknown argument ${CL_ARG}"
            exit 1
            ;;
    esac
    
done

BUILD_NUM=$1

echo "Installing dists from ${CONTAINER_DIR} to ${UPDATE_DIR} with build number ${BUILD_NUM}"

install_dist()
{
    DIST_SRC_PREFIX="$1"
    DIST_DST_PREFIX="$2"

    UPDATE_FILE="${UPDATE_DIR}/${DIST_DST_PREFIX}-${BUILD_NUM}.zip"
    cp ${CONTAINER_DIR}/${DIST_SRC_PREFIX}-dist-*.zip ${UPDATE_FILE}
    ~/bin/md5file.sh "${UPDATE_FILE}"
}

set -e
set -v

install_dist "dist/target/container" "update"
install_dist "cloudlet-dist/target/container-cloudlet" "update-cloudlet"
install_dist "shared-server/groovy-dist/target/container-groovy" "update-groovy"
install_dist "proxy/bridge-dist/target/container-proxy-bridge" "update-proxy-bridge"
install_dist "proxy/client-dist/target/container-proxy-client" "update-proxy-client"
install_dist "shared-server/embedded-db-dist/target/container-embedded-db" "update-embedded-db"
install_dist "shared-server/http-dist/target/container-shared-server-http" "update-shared-server-http"
install_dist "shared-server/extended-security-dist/target/container-extended-security" "update-extended-security"

~/bin/release_container.sh ${BUILD_NUM}

