#!/bin/bash

. env.sh

usage()
{
    echo "Installs all the distribution files from a local container build to a local platform instance."
    echo 
    echo "Usage: `basename $0` [-c <container_dir>] [-u <update_dir>] "
    exit 1
}

while [ $# -gt 1 ] ; do

    CL_ARG=$1
    shift

    case ${CL_ARG} in

        -c)
            ATOM_SRC_DIR=$1
            shift
            ;;

        -u)
            PLATFORM_UPDATES_DIR=$1
            shift
            ;;
        -h)
            usage
            ;;
        *)
            echo "Unknown argument ${CL_ARG}"
            exit 1
            ;;
    esac
    
done

BUILD_NUM=$(get_atom_version)

echo "Installing dists from ${ATOM_SRC_DIR} to ${PLATFORM_UPDATES_DIR} with build number ${BUILD_NUM}"


echo -n "Continue? [y\\N] "
read answer

if [ "${answer}" != "y" ]
then
    echo "Aborting"
    exit 127
fi

install_dist()
{
    DIST_SRC_PREFIX="$1"
    DIST_DST_PREFIX="$2"

    UPDATE_FILE="${PLATFORM_UPDATES_DIR}/${DIST_DST_PREFIX}-${BUILD_NUM}.zip"
    cp ${ATOM_SRC_DIR}/${DIST_SRC_PREFIX}-dist-*.zip ${UPDATE_FILE}
    md5file.sh "${UPDATE_FILE}"
}

set -e
set -v

install_dist "dist/target/container" "update"
install_dist "cloudlet-dist/target/container-cloudlet" "update-cloudlet"
install_dist "shared-server/groovy-dist/target/container-groovy" "update-groovy"
install_dist "proxy/bridge-dist/target/container-proxy-bridge" "update-proxy-bridge"
install_dist "proxy/client-dist/target/container-proxy-client" "update-proxy-client"
install_dist "shared-server/embedded-db-dist/target/container-embedded-db" "update-embedded-db"
install_dist "shared-server/http-dist/target/container-shared-server-http" "update-shared-server-http"
install_dist "shared-server/extended-security-dist/target/container-extended-security" "update-extended-security"
install_dist "shared-server/mllp-dist/target/container-shared-server-mllp" "update-shared-server-mllp"
install_dist "shared-server/queue-dist/target/container-shared-server-queue" "update-shared-server-queue"

release_container.sh ${BUILD_NUM}

